### ISSUE TITLE
Format on save option and ctrl+alt+f do nothing

### ISSUE THREAD

**Issue by leshow** [jlongster/prettier-atom#10]
I can manually select to prettify but selecting format on save or doing ctrl+alt+f both do nothing on .js files
```
❯ atom --version
Atom    : 1.12.0
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0
```

**Comment by just-boris** [comment]
Have you got any warnings after install?

I have got it, as I have described in #5

Installation has failed, so plugin does nothing.

**Comment by jlongster** [comment]
See above comment, it probably was failing to install for you. Try to latest version of prettier-atom, it should work.
