### ISSUE TITLE
The format will clean the annotation in jsx file at the same time in Atom

### ISSUE THREAD

**Issue by shixukai** [jlongster/prettier-atom#11]
It's a excellent package! l like it.

But I think this should not happen when I format the JSX file the annotation was cleaned automatically  by prettier-atom.

before format
![image](https://cloud.githubusercontent.com/assets/12314563/21831285/8f0f585c-d7dd-11e6-9bb9-5df8c62273a4.png)

after format
![image](https://cloud.githubusercontent.com/assets/12314563/21831300/a325c934-d7dd-11e6-8032-2072f290ddcb.png)

The animation is gone, please take a look, thanks.

**Comment by jlongster** [comment]
What do you mean animation? I see that the dangling comments are gone, and that is a known issue. Please file prettier bugs at https://github.com/jlongster/prettier, not here.
