### ISSUE TITLE
Anyone want to take over maintanence?

### ISSUE THREAD

**Issue by jlongster** [jlongster/prettier-atom#13]
I don't use Atom daily, and I feel someone who uses it as their primary editor is more suited to maintain this. Also I won't have time to watch this as much as prettier itself. I'm happy to move this project to someone else's account if they want to be the core maintainer.

**Comment by robwise** [comment]
I'd be very interested. My day job is full stack engineer focusing mainly on Rails and React ([my personal website](robwise.github.io)). I'd been contributing to [this project](https://github.com/shakacode/react_on_rails), but have not done much OSS recently and want to get back into it.

P.S. - Did you go to UVA and live in Bonnycastle first year?

**Comment by oviava** [comment]
I would be interested, however I think the project should still remain under your account.

**Comment by jlongster** [comment]
Cool. @robwise I added you. I don't think this is going to take much, but @oviava if you're still interested, I can add you to.

I will still try to watch the PRs.

**Comment by oviava** [comment]
@jlongster sure thing
