### ISSUE TITLE
Avast issue with prettier-atom v0.0.6 install

### ISSUE THREAD

**Issue by stoe** [jlongster/prettier-atom#19]
~~Just wanted to let you know package installs just fine, but the below Avast infection is reported.~~

Can't install v0.0.6 due to the below warning.

![image](https://cloud.githubusercontent.com/assets/203805/21954023/c231e2ca-da46-11e6-9e28-90b595c93d18.png)

Using `apm install prettier-atom@0.0.5` installs without the infection message, but using `apm install prettier-atom` or `apm update` raises the above infection warning from Avast.

![image](https://cloud.githubusercontent.com/assets/203805/21954041/256b0f88-da47-11e6-9ee2-c17858cd40f4.png)

Same behaviour if trying to install via Atom directly.

**Comment by stoe** [comment]
Checking again, I can't seem to install v0.0.6 at all without the above infection warning.

**Comment by robwise** [comment]
@stoe I think this seems to be an issue with Prettier and not prettier-atom. I think we should close this and refer people to your [issue](https://github.com/jlongster/prettier/issues/193) there?
