### ISSUE TITLE
Respect Atom's "Tab Length" setting 

### ISSUE THREAD

**Issue by elstob** [jlongster/prettier-atom#2]
It appears the prettifier defaults to 2 spaces per tab. I imagine this should/could be configurable in the package settings but ideally it would use the value set in Settings > Editor > Tab Length by default.

**Comment by jlongster** [comment]
Good point. The default value could be read from that unless it's explicitly set in the settings.

**Comment by oviava** [comment]
@jlongster If you get this into `prettier` as an option I can make the changes to `prettier-atom`

**Comment by danseethaler** [comment]
+1 for reading from the editor configuration `".js.jsx.source": editor: tabLength: x`. This would make the package for me.

**Comment by jlongster** [comment]
@oviava This doesn't have anything to do with `prettier`. The atom package itself should read this value and pass it to prettier if the user hasn't set a value in the plugin's config.

**Comment by robwise** [comment]
@oviava Do you want to take this one or should I?

**Comment by oviava** [comment]
@jlongster I don't remember seing an option for tab length in prettier - I was thinking it has to be implemented there. I'll have a look and try to submit a PR.

**Comment by robwise** [comment]
@oviava It's in Prettier and also in the atom plugin, but right now it's manually set. So I guess we should make it so that it feeds the current editor's tab length setting by default, unless the user has chosen to override that tab length manually via the settings.

**Comment by oviava** [comment]
@robwise noticed it, not sure how I missed it. yeah, should be a quick PR - however I think you can set the option for either global or for specific source files - should we get the global option or just .js / .jsx ?

**Comment by robwise** [comment]
@oviava I'm pretty sure you can query the active editor for exactly what tab length the user is currently using for the specific tab they are in. Some people use autodetect because they switch around projects with different styles, so I don't think we can rely on looking for `.jsx` or `.js`, and that won't work in blank tabs that haven't been saved yet.

**Comment by oviava** [comment]
@robwise did a PR, think I'm conflicting with some of your changes, mind having a look ? cheers.
