### ISSUE TITLE
shebang wrongly prettified

### ISSUE THREAD

**Issue by stoe** [jlongster/prettier-atom#20]
The shebang (e.g. `#!/usr/local/bin/node`) shouldn't be prettified to `///usr/local/bin/node` 

![](https://cl.ly/1Z3l1B132h0m/Screen%20Recording%202017-01-14%20at%2011.09.gif)

**Comment by stoe** [comment]
Sorry, should have been reported in https://github.com/jlongster/prettier.

It was reported in https://github.com/jlongster/prettier/issues/44, but wrongly prettified issue still remains.

**Comment by demoneaux** [comment]
I believe this should have been fixed in 0.0.6. Please try updating your plugin.

**Comment by stoe** [comment]
I tried, but have issues doing so as the update is blocked with an infection warning from Avast.
See https://github.com/jlongster/prettier-atom/issues/19

**Comment by robwise** [comment]
Closing this one since as you said it's a Prettier bug.
