### ISSUE TITLE
Possible Regression with Ignore Settings

### ISSUE THREAD

**Issue by robwise** [jlongster/prettier-atom#25]
@jlongster I was looking at the CHANGELOG because I'm planning on getting that back on track, but I noticed [this line](https://github.com/jlongster/prettier-atom/commit/d529318af8edbfd5272448d4fdc5a72245a45f98#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR7) and am worried there was a regression with the changes I made in https://github.com/jlongster/prettier-atom/pull/22. 

Can you give more insight on what behavior this is describing, and I can make sure it is put back in?

Also, the release numbers in the CHANGELOG do not seem to correlate with the release tags. Should I squash all of them into one `v0.0.1` release and then add what we've done since then?

**Comment by jlongster** [comment]
@robwise We should remove the changelog. I forked the [standard-formatter](https://atom.io/packages/standard-formatter) project to make this we've just inherited it. We should blow it away and make a new one (if we want it).
