### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by robwise** [jlongster/prettier-atom#28]
As per https://github.com/jlongster/prettier-atom/issues/25#issuecomment-273204553, we should probably blow away the current changelog and then create a new one from scratch that gets us back up to date.

**Comment by jlongster** [comment]
I removed the current one at least. Not sure a small project of this size warrants a full changelog as it's pretty easy to look at the commit history and read the 1-3 commits between versions. But I'll leave that up to you as the maintainer :)

I'm happy to add you to the release process btw. Do I just add you as an "owner" to the npm project and `apm publish` just works?

**Comment by robwise** [comment]
Actually, I never actually checked, I was just assuming. Maybe I already am able to by nature of being a GitHub collaborator? Next time that Prettier gets bumped, I will try and see if I can do it.

**Comment by robwise** [comment]
Okay, turns out I can publish, so all set! Sorry about that!

**Comment by robwise** [comment]
After merging prettier-eslint we're adopting the [commitizen](https://github.com/commitizen/cz-cli) + [cz-conventional-changelog](https://www.npmjs.com/package/cz-conventional-changelog) we should be able to auto-generate one. I just need to figure it out.
