### ISSUE TITLE
Get config from eslint

### ISSUE THREAD

**Issue by danielbuechele** [jlongster/prettier-atom#3]
I guess we would need to write a custom translation from eslint-rules to prettier config, but it would be super cool to get at least the most basic rules like tabs/spaces, trailing commas, etc. from the eslint-file.

**Comment by jlongster** [comment]
There are some discussion on the prettier repo about this, please file issues and talk about it over there (https://github.com/jlongster/prettier).

Long story short, we are not going to do this in the short-term. We will work on ways to make it easy to integrate with eslint but prettier itself will not read from it, but another higher-level tool could.
