### ISSUE TITLE
version still at 0.0.7

### ISSUE THREAD

**Issue by bsr203** [jlongster/prettier-atom#30]
The version at https://atom.io/packages/prettier-atom is still  0.0.7. Anything needed to bump to 0.0.8 ? or does it take more than a day to update the registry.

**Comment by robwise** [comment]
@jlongster Has to publish it as I don't believe I have that ability

**Comment by jlongster** [comment]
I published 0.0.8 yesterday but there was an obscure error at the end. I really hate the `apm publish` workflow.

**Comment by jlongster** [comment]
It should should be updated to 0.0.9. Please check and re-open if not!

**Comment by bsr203** [comment]
thank you. Atom detected the update as available, and upgraded to 0.0.9.
