### ISSUE TITLE
"Single quote" property not working as expected

### ISSUE THREAD

**Issue by jjwyse** [jlongster/prettier-atom#35]
I currently have the "Single Quote" property in Atom set to `true`, however when I format the code using `prettier`, it is changing all single quotes to double quotes.

![Properties](https://cl.ly/3x3t251m0E1j/Screen%20Shot%202017-01-30%20at%209.57.10%20AM.png)

Formatting code:
![GIF](https://cl.ly/1W272G2Z2S0r/Screen%20Recording%202017-01-30%20at%2010.00%20AM.gif)

Anyone else experiencing this or did I screw something up somewhere?

**Comment by robwise** [comment]
@jjwyse I think this is an issue relating to Prettier itself as it's treating JSX attributes specially. You will notice that Prettier is not changing the single quotes at the top in your imports, so it is respecting the option that the atom plugin has set.

**Comment by demoneaux** [comment]
Yep, since JSX was designed to be similar to HTML, the convention is to use double quotes for JSX attributes.

**Comment by jjwyse** [comment]
@robwise @demoneaux - Ah, nice - thanks for the response and insight, appreciate it.  I'll go ahead and close this.  Thanks again. 👍

**Comment by Imran-Haider313** [comment]
Why No one mentioned this [option](https://prettier.io/docs/en/options.html#jsx-quotes)

**Comment by robwise** [comment]
Because it didn't exist 3 years ago
