### ISSUE TITLE
Save without formatting

### ISSUE THREAD

**Issue by tacomanator** [jlongster/prettier-atom#41]
What do you think of a key combo to bypass formatting and save? Sometimes I have to temporarily disable the `Format on Save` setting to make patches for OSS/projects that don't use prettier.

**Comment by robwise** [comment]
@tacomanator I'm not sure how I would go about coding that one. Maybe it would be better if we had a whitelist or blacklist of globs. I did a PR for a related project that does blacklist globs:

https://github.com/kentcdodds/prettier-eslint-atom/pull/11/files

Then you would just blacklist the projects you didn't want it for. What do you think of that solution?

**Comment by tacomanator** [comment]
@robwise that would definitely help. I haven't thought of a better way either.

**Comment by Anthonyzou** [comment]
I just had this exact issue recently. It would be nice to ignore `souce.min.js` type files.

**Comment by robwise** [comment]
I'm currently work on a PR that will integrate `prettier-eslint-atom` where I wrote this feature, so stay tuned!

**Comment by robwise** [comment]
@Anthonyzou @tacomanator We now have the ability to both whitelist and blacklist certain globs so I'm closing this for now. Maybe in the future we should add a keymap to toggle format on save on and off.
