### ISSUE TITLE
Adding the ability to fail silently

### ISSUE THREAD

**Issue by oriSomething** [jlongster/prettier-atom#45]
Current behave is that when I save a document that cannot be converted to AST, I get a huge popover of the failure of `prettier-atom`.
I think adding the ability that it will fail silently and won't be trigger the popover can be very helpful since, It's not exactly a pleasant UX.
Of course, I can try making a PR if needed.

Thanks!

**Comment by robwise** [comment]
Yeah, great idea! Do you think you can try to tackle this one in a PR? I think we can just have a simple checkbox that lets you silence the errors? Does it do this only on format-on-save, or even if you invoke the command manually?

**Comment by oriSomething** [comment]
- Yes, i'll try to PR this
- I though on a simple checkbox too
- If you invoke manually the command. It might won't be a good idea

**Comment by erbridge** [comment]
I actually find those errors very helpful. They usually occur because of syntax issues I had missed. But perhaps they could highlight the error instead of making such a huge stack trace?

**Comment by oriSomething** [comment]
@erbridge It's seems to me like a valid option. But, I don't think it should come instead of the "silent failure"

**Comment by robwise** [comment]
Yeah we could have another option which is `errors include stack trace` or something? And that one applies to everything and not just the format on save?

**Comment by robwise** [comment]
I'm going to close this for now, discussion of removing stack trace moved to https://github.com/jlongster/prettier-atom/issues/49
