### ISSUE TITLE
Decorators throw SyntaxError

### ISSUE THREAD

**Issue by zepod** [jlongster/prettier-atom#48]
Encountered issue with decorators. After prettying .jsx file with decorators in it, following message is displayed and file isn't prettyfied. 

Here are screenshot of error message and full stack trace.

![prettier-atom-issue](https://cloud.githubusercontent.com/assets/19804724/22925223/2d996708-f2a8-11e6-931b-56602a3990f4.png)
![atom-prettier-issue-2](https://cloud.githubusercontent.com/assets/19804724/22925281/5fe5f65e-f2a8-11e6-894c-efbc357b2e62.png)
![atom-prettier-issue-3](https://cloud.githubusercontent.com/assets/19804724/22925293/691d70ee-f2a8-11e6-9614-8bf1aa789ca1.png)

**Comment by robwise** [comment]
@zepod Is this a prettier-atom issue or a prettier issue?

**Comment by difelice** [comment]
Not quite sure, the following code works fine with client `prettier@1.7.2` and website playground.

## Snippet
```js
@decorator @another
class Test {
}
```

## Error
```
prettier-atom failed: Unexpected token @ (1:1)

1 | @decorator @another | ^ 2 | class Test { 3 | }
```

## Prettier Playground
https://prettier.io/playground/#%7B%22content%22%3A%22%40decorator%20%40another%5Cnclass%20Test%20%7B%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D
