### ISSUE TITLE
Bad indentation on comment blocks

### ISSUE THREAD

**Issue by darahak** [jlongster/prettier-atom#50]
I ran the latest version `0.17.0` on a script that defines a RequireJS module.
It added one indentation step to the whole module, but the comment blocks didn't follow (just the first line).

Here's an example (with 4-space tabs):

```js
define('zzz', [
    'a',
    'b',
    'c'
], function (a, b, c) {
    /**
     * Does something.
     * @return {void}
     */
    function doSomething() {
        ...
    }

    ...
});
```

became

```js
define(
    'zzz',
    [
        'a',
        'b',
        'c'
    ],
    function (a, b, c) {
        /**
     * Does something.
     * @return {void}
     */
        function doSomething() {
            ...
        }

        ...
    }
);
```

It works properly when I test my code on the [REPL](https://jlongster.github.io/prettier/) though.
Can other packages interfere when Prettier runs in Atom?

**Comment by robwise** [comment]
Hmm, this is strange. I'm not sure off the top of my head what the culprit here may be. To answer your question, yes other packages could interfere I suppose if you were using something like eslint's fix-on-save feature, but I'm not sure why that would cause this.

**Comment by darahak** [comment]
It looks like this one: https://github.com/prettier/prettier/issues/648

**Comment by robwise** [comment]
@darahak Does that mean we should close here and that it's actually a prettier issue?

**Comment by darahak** [comment]
@robwise Yes, I will follow this other issue instead. We can always re-open if necessary.
