### ISSUE TITLE
Issue with eslint and JSX

### ISSUE THREAD

**Issue by keul** [jlongster/prettier-atom#58]
On a react.js project with eslint atom plugin configured, if I use the prettier format I get this code:

    return [
      (
        <div>
          <input
            type="checkbox"
            name="invalidateCache"
            id={uniqueId}
            onChange={this.onInvalidateCache}
            checked={this.props.workflowDataStorage.cacheInvalidation}
          />
          <label htmlFor={uniqueId}>Invalidate cache on requests</label>
        </div>
      )
    ];

... but eslint raise a warning:

![schermata 2017-03-01 alle 15 18 16](https://cloud.githubusercontent.com/assets/284924/23463597/6264a7fe-fe92-11e6-8887-1b9f88d3cab7.png)

So it seems that eslint is happy with a code like this:

    return [
      (
      <div>
        <input
          type="checkbox"
          name="invalidateCache"
          id={uniqueId}
          onChange={this.onInvalidateCache}
          checked={this.props.workflowDataStorage.cacheInvalidation}
        />
        <label htmlFor={uniqueId}>Invalidate cache on requests</label>
      </div>
    )
    ];

Although the code formatted by prettier-atom is nicer IMHO, I'm wondering how to make eslint and this coexists. Maybe is a bug in eslint/jsx but I've no element to know.

Any hint?

**Comment by robwise** [comment]
@keul I am currently working on integrating `prettier-eslint` into this repo. Until that's ready, I would check out https://github.com/kentcdodds/prettier-eslint-atom
