### ISSUE TITLE
Option for colon insertion

### ISSUE THREAD

**Issue by negebauer** [jlongster/prettier-atom#60]
I don't like having `;` at the end of each line, which this beautifier forces.
It would be good to have it as an option that can be turned off

**Comment by robwise** [comment]
@negebauer If you want this to be an option in [prettier](https://github.com/prettier/prettier) itself, please make an issue there.

Also, not sure if this interests you, but I will be soon merging in the [prettier-eslint-atom](https://github.com/kentcdodds/prettier-eslint-atom) repo, in which case if you use ESlint, you can make sure your semicolon ESLint rule is configured and it will automatically remove them for you.

Closing for now, let me know if you have any more questions.

**Comment by negebauer** [comment]
@robwise Nice, the eslint will do
I'm actually running lint --fix before committing as a workaround
