### ISSUE TITLE
Apply excludedGlobs

### ISSUE THREAD

**Issue by kentcdodds** [jlongster/prettier-atom#73]
:wave: hi! Unless I'm missing something `excludedGlobs` isn't actually being applied anywhere...

**Comment by robwise** [comment]
*sigh* 3rd bug. I'm on it!

**Comment by kentcdodds** [comment]
Thank you!

**Comment by rotexhawk** [comment]
I am still having an issue with this. I have .html in my list of exclude globs and it ignores it. 
It messes up my .html files but if I turn off format on save, .html file looks good.

**Comment by fostimus** [comment]
Does this work with directories? For example,  all files within the directory excludeMe `*/excludeMe/*`

**Comment by robwise** [comment]
It should, see https://git-scm.com/docs/gitignore for syntax
