### ISSUE TITLE
format-on-save seems to break plugins such as linter-eslint

### ISSUE THREAD

**Issue by ryancole** [jlongster/prettier-atom#86]
I'm here to report an unexpected interaction, between atom plugins, that I notice while using both prettier-atom and linter-eslint.

If you enable prettier-on-save and save a document, it'll cause linter's inline error highlighting and gutter icons to break. They'll disappear until you continue typing again, etc. I believe it's the prettier-atom plugin changing the text that causes the linter plugin to no re-draw its inline error icons, etc.

I had initially opened an issue about this on [linter's repository](https://github.com/steelbrain/linter/issues/1345). Through that issue, I feel as though I have narrowed this issue down to prettier-atom's format-on-save feature. I asked, there, about what prettier-atom could do to perhaps play more nicely with the linter plugin (ideally any other plugin that would need to know to re-draw stuff, but in this specific case just linter). [It was suggested](https://github.com/steelbrain/linter/issues/1345#issuecomment-286224599), in my linter issue, that prettier-atom could trigger `linter:lint` command on the text editors *after* prettier-atom is done with them.

Now, I can see this fix being a slippery slope in your eyes, because it'd suck to get into a situation where prettier-atom needs to trigger commands from all other plugins, etc. So, with that said, I just wanted to open this issue so that a discussion can happen as to how to make this plugin be a bit friendlier to other plugins that have drawn stuff on text editors, etc.

**Comment by robwise** [comment]
@ryancole Oh I've been noticing this as well, but couldn't figure out why it was happening.

> Now, I can see this fix being a slippery slope in your eyes, because it'd suck to get into a situation where prettier-atom needs to trigger commands from all other plugins, etc

True, but because we specifically have an ESlint integration, I think fixing unexpected `linter-eslint` problems should be considered in-scope for this repo. If it was some obscure unrelated package then I might be more wary of trying to fix it. I will mark this as a bug and hopefully come up with a fix soon. 

Thank you so much for taking the time to investigate this and link the discussions.

**Comment by steelbrain** [comment]
Just a side note that if you trigger the `linter:lint` command on the editor, it'll fix this issue for not just ESLint, but all of the linter providers

**Comment by robwise** [comment]
@steelbrain roger that, good to know, I'll make sure to use that more generic command and not a linter-eslint-specific command
