### ISSUE TITLE
[HELP] semi rule in atom

### ISSUE THREAD

**Issue by artembloom** [jlongster/prettier-atom#91]
Hello!
I have this eslint config:
```
{
    "parser": "babel-eslint",
    "env": {
        "browser": true
    },
    "ecmaFeatures": {
      "jsx": true
    },
    "plugins": [
        "jsx-a11y",
        "import",
        "react",
        "react-native"
    ],
    "extends": "airbnb",
    "rules": {
      "react/jsx-filename-extension": ["error", { "extensions": [".js", ".jsx"] }],
      "semi": ["error", "never"],
      "comma-dangle": ["error", "never"],
      "arrow-parens": ["error", "always"]
    }
}
```

As you can see  "semi": ["error", "never"]
I set ESLint integration in settings and Format on Save
Everything is doing fine, but sometimes prettier adds semi in the end of expression. Not everywhere, i find it on object statements or similar like this (react component class)

```
state = {
    loading: true
  };
```

in

```
class Example extends React.Component {
  state = {
    loading: true
  };

  render() {
    // some code
  }
}

export default Example
```

How can I fix it? Or is this a bug?
Thanks a lot.

**Comment by robwise** [comment]
Hey @artembloom, can you do me a favor and check if you do the same thing with the [prettier-eslint-cli](https://github.com/prettier/prettier-eslint-cli) tool on that file? If it still happens, then this is an error with that library and not this plugin as we just call that under the hood.

**Comment by artembloom** [comment]
Hey @robwise. The same result. And I find that it happens only in react component class on state and arrows functions as methods of class. This is example:

```
class Example extends React.Component {
  
  state = { imageLoading: true };

  onImageLoadStart = () => this.setState({ imageLoading: true });

  onImageLoadEnd = () => this.setState({ imageLoading: false });

  render() {
    // some code
  }
}
```

**Comment by robwise** [comment]
@artembloom If you get the same result, that means it is a prettier-eslint bug and not a prettier-atom bug. Could you make an issue there since I can't fix it on this repo?

**Comment by artembloom** [comment]
Yeah, sure!
