### ISSUE TITLE
ESLint integration does not seem to use .eslintrc.js files.

### ISSUE THREAD

**Issue by aickin** [jlongster/prettier-atom#93]
First, thanks for all your hard work on prettier! In hopes of making it even better, I'd like to share an issue I found today.

**Short repro instructions:**

1. Clone the React codebase.
1. Open up the master branch in Atom and go to prettier-atom settings. Turn ESLint integration on and enable Format on Save. Leave all other settings as their defaults.
1. Add a space to any file of significant length (`ReactDOMComponent.js`, for example) and save.
1. `git diff` will show that lots of changes have been introduced by prettier-atom.

**Expected Behavior:** Since the React codebase has already been formatted with prettier, using prettier-atom shouldn't introduce changes.

**Longer narrative explanation:**
I installed prettier-atom to work on React pull requests, hoping to get fix-on-save. My first attempt to get prettier-atom working was to check the "ESLint integration" checkbox and make sure my linter plugin did *not* have fix on save, as was documented. Unfortunately, though, this caused a bunch of unrelated reformats of the React code base (changing double quotes back to single, adding bracket spacing, etc.). After playing around a bit, I found that changing React's `.eslintrc.js` file to JSON and renaming `.eslintrc` made ESLint integration work basically as expected.

I'm pretty sure what is happening is that prettier-atom doesn't recognize all the forms of ESLint config, documented [here](http://eslint.org/docs/user-guide/configuring#configuration-file-formats).

Again, thanks for your hard work!

**Comment by robwise** [comment]
@aickin Thanks for reporting this! I think you're right, but I believe that this is a problem with prettier-eslint. Do you think you could report this same issue there? (You can tell by installing prettier-eslint-cli and running it on the code, and if it still has the problem, then it needs to be changed in prettier-eslint and not this plugin).
