### ISSUE TITLE
special chars in strings

### ISSUE THREAD

**Issue by rmetzler** [jlongster/prettier-atom#95]
Prettier and Prettier-Atom do replace special chars like "äöüß" in Strings with another representation.

```js
var test = "äöüß";
```
becomes
```js
var test = "\xE4\xF6\xFC\xDF";
```

Is there a way to deactivate this behavior?

**Comment by robwise** [comment]
@rmetzler Can you open an issue on the prettier repo? This plugin just calls prettier on the text under the hood.

**Comment by rmetzler** [comment]
Thank you, I opened jlongster/prettier-atom#95 as suggested.

But if there is a code change in prettier which adds a commandline switch to change behavior, there would be changes needed in prettier-atom too.

**Comment by robwise** [comment]
@rmetzler Roger that, let me know if such a change is made and I will reopen to support it
